/**
 * Generates src/app/styles/tokens.css from design/icyre-tokens.json
 * (a copy of the ICYRE Design System tokens). Run: `bun run tokens`.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

interface Token {
  name: string;
  value: string | Record<string, string>;
}
interface TypeStyle {
  name: string;
  fontSize: string;
  lineHeight: string;
  fontWeight: number;
  letterSpacing?: string;
}
interface Tokens {
  color: { tokens: Token[] };
  type: { families: Record<string, string>; groups: { styles: TypeStyle[] }[] };
  [family: string]: unknown;
}

const root = new URL('..', import.meta.url);
const source = fileURLToPath(new URL('design/icyre-tokens.json', root));
const target = fileURLToPath(new URL('src/app/styles/tokens.css', root));

const tokens = JSON.parse(readFileSync(source, 'utf8')) as Tokens;

// Aliases like "{ice-50}" become var(--ice-50); themed values use the first (light) theme.
const cssValue = (value: Token['value']): string => {
  const v = typeof value === 'string' ? value : (Object.values(value)[0] ?? '');
  return v.replace(/\{([A-Za-z0-9_.-]+)\}/g, 'var(--$1)');
};

const families = ['color', 'gradient', 'spacing', 'radius', 'shadow', 'borderWidth', 'opacity', 'duration', 'easing', 'layout', 'zIndex'];

const lines: string[] = [
  '/*',
  ' * ICYRE design tokens — GENERATED by scripts/generate-tokens.ts from design/icyre-tokens.json.',
  ' * Do not edit by hand. Product code uses semantic tokens (background, surface, text-*, …),',
  ' * never primitives (ice-*, electric-*, holo-*).',
  ' */',
  ':root {',
];

for (const family of families) {
  const group = tokens[family] as { tokens: Token[] } | undefined;
  if (!group) continue;
  lines.push(`  /* ${family} */`);
  for (const t of group.tokens) lines.push(`  --${t.name}: ${cssValue(t.value)};`);
}

lines.push('  /* type */');
for (const [name, stack] of Object.entries(tokens.type.families)) lines.push(`  --font-${name}: ${stack};`);
for (const group of tokens.type.groups) {
  for (const s of group.styles) {
    const p = `--type-${s.name}`;
    lines.push(`  ${p}-size: ${s.fontSize};`, `  ${p}-line: ${s.lineHeight};`, `  ${p}-weight: ${s.fontWeight};`);
    lines.push(`  ${p}-tracking: ${s.letterSpacing ?? '0'};`);
  }
}
lines.push('}', '');

writeFileSync(target, lines.join('\n'));
console.log(`tokens.css written (${lines.length} lines)`);
