global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: catalog-service
    metrics_path: /metrics
    static_configs:
      - targets: ["catalog:8080"]
        labels:
          service: catalog-service

  - job_name: web-bff
    metrics_path: /metrics
    static_configs:
      - targets: ["bff:8080"]
        labels:
          service: web-bff

  - job_name: auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:8080"]
        labels:
          service: auth-service

  - job_name: user-profile-service
    metrics_path: /metrics
    static_configs:
      - targets: ["user-profile:8080"]
        labels:
          service: user-profile-service

  - job_name: stream-auth-service
    metrics_path: /metrics
    static_configs:
      - targets: ["stream-auth:8080"]
        labels:
          service: stream-auth-service
